### ISSUE TITLE
[FEATURE] How to dynamically transfer parameters in SpringBoot Bean Chat Language Model

### ISSUE THREAD

**Issue by lbjfish** [langchain4j/langchain4j-spring#15]
**Spring Boot , i want to dynamically call params，but it is limited too die:**

```
@Bean
    public ChatLanguageModel myCustomChatModel() {
        return OpenAiChatModel.builder()
                .apiKey("dynamically ")
                .stop(dynamically )
                .topP(dynamically )
                .temperature(dynamically )
                .modelName("dynamically ").build();
    }
```

**Comment by Yunie9** [comment]
你可能需要重写一个OpenAiChatModel，重载generate方法 提供额外的参数来覆盖默认的配置。在不重写OpenAiChatModel的情况下，可以考虑使用代理模式，例如有多个API key，可以为每个api key维护一个OpenAiChatModel实例，然后根据一定的策略来动态选择需要使用哪一个实例来执行generate

**Comment by langchain4j** [comment]
Closing as a duplicate of https://github.com/langchain4j/langchain4j/issues/837
